Re-add openMPI selection in the configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10,7 +10,6 @@
 configure=$0
 build_top=$PWD
 
-have_cuda=no
 cuda_path=
 cuda_check=include/cuda.h
 enable_cuda=
@@ -19,8 +18,15 @@ have_openmpi=no
 openmpi_path=
 openmpi_check=include/mpi.h
 
+enable_python=
+
+# NCCL communication library
+have_nccl=no
+nccl_path=
+nccl_check=include/nccl.h
+
 # CNTK Custom MKL Version
-cntk_custom_mkl_version=1
+cntk_custom_mkl_version=2
 
 have_mkl=no
 mkl_path=
@@ -34,6 +40,10 @@ openblas_check=include/openblas_config.h
 # Boost library
 boost_path=
 boost_check=include/boost/test/unit_test.hpp
+
+# Protocol buffers library
+protobuf_path=
+protobuf_check=lib/libprotobuf.a
 
 have_kaldi=no
 kaldi_path=
@@ -67,6 +77,15 @@ have_libzip=no
 libzip_path=
 libzip_check=include/zip.h
 
+have_swig=no
+swig_path=
+swig_check=bin/swig
+swig_required_version=3.0.10
+
+py_check=bin/python
+py_versions=
+declare -A py_paths
+
 mathlib=
 
 default_use_1bitsgd=no
@@ -74,6 +93,9 @@ enable_1bitsgd=$default_use_1bitsgd
 
 default_use_code_coverage=no
 enable_code_coverage=$default_use_code_coverage
+
+default_use_asgd=yes
+enable_asgd=$default_use_asgd
 
 # List from best to worst choice
 default_path_list="/usr /usr/local /opt /opt/local"
@@ -86,13 +108,16 @@ default_boost="boost-1.60.0"
 
 # NOTE: Will get compilation errors with cuda-6.0
 default_cudas="cuda-7.5 cuda-7.0 cuda-6.5"
+default_nccls="nccl"
 default_kaldis="kaldi-trunk kaldi-c024e8aa"
 default_gdk_includes="include/nvidia/gdk"
 default_gdk_nvml_libs="src/gdk/nvml/lib"
 default_cubs="cub-1.4.1"
-default_cudnns="cudnn-4.0"
+default_cudnns="cudnn-5.1 cudnn-5.0"
 default_opencvs="opencv-3.1.0 opencv-3.0.0"
+default_protobuf="protobuf-3.1.0"
 default_libzips="libzip-1.1.2"
+default_swig="swig-3.0.10"
 default_openmpis="openmpi-1.10.1"
 
 function default_paths ()
@@ -151,6 +176,16 @@ function find_boost ()
     find_dir "$default_boost" "$boost_check"
 }
 
+function find_protobuf ()
+{
+    find_dir "$default_protobuf" "$protobuf_check"
+}
+
+function find_nccl ()
+{
+    find_dir "$default_nccls" "$nccl_check"
+}
+
 function find_cuda ()
 {
     find_dir "$default_cudas" "$cuda_check"
@@ -202,6 +237,15 @@ function is_hardlinked ()
     echo $r
 }
 
+function check_version ()
+{
+    local expected_version=$1
+    local actual_version=$2
+    [ -z "$actual_version" ] && return 1
+    [ "$( printf "%s\n" $actual_version $expected_version | sort -V | head -1)" = "$expected_version" ]
+    return $?
+}
+
 function default_use_cuda ()
 {
     if test x$(find_cuda) = x || test x$(find_gdk_include) = x || test x$(find_gdk_nvml_lib) = x || test x$(find_cudnn) = x || test x$(find_cub) = x
@@ -212,6 +256,66 @@ function default_use_cuda ()
     fi
 }
 enable_cuda=$(default_use_cuda)
+
+# TODO allow to pick up from path?
+function check_swig ()
+{
+    local swig_dir="$1"
+    local swig_bin="$swig_dir/$swig_check"
+
+    # Check that binary is executable and we can retrieve the version
+    test -x "$swig_bin" || return $?
+    "$swig_bin" -version 2>&1 1>/dev/null || return $?
+
+    local actual_version=$("$swig_bin" -version | grep '^SWIG Version ' | head -1 | grep -o '[0-9.]*')
+    if check_version "$swig_required_version" "$actual_version"
+    then
+        echo "$swig_dir"
+        return 0
+    else
+        return 1
+    fi
+}
+
+function find_swig ()
+{
+    check_swig "$(find_dir "$default_swig" "$swig_check")"
+}
+
+function check_python ()
+{
+    # Required version: exact match against major and minor version
+    local required_version="$1"
+    local py_dir="$2"
+    local py_bin="$py_dir/$py_check"
+    [ -x "$py_bin" ] || return 1
+    local py_version=$("$py_bin" -c "import sys; sys.stdout.write('{0}{1}'.format(sys.version_info.major,sys.version_info.minor))")
+    [ "$?" = "0" ] && [ -x "$py_bin" ] && [ "$py_version" = "$required_version" ] && {
+        echo $py_dir
+        return 0
+    }
+    return 1
+}
+
+# TODO allow to pick up from path?
+function find_python ()
+{
+    local required_version="$1"
+    local py_dir=$(find_dir "" "$py_check")
+    check_python "$required_version" "$py_dir"
+}
+
+function default_use_python ()
+{
+# Keeping it default "no" for a little while:
+#    if test x$(find_swig) = x || test x$(find_python 34)$(find_python 35) = x
+#    then
+        echo no
+#    else
+#        echo yes
+#    fi
+}
+enable_python=$(default_use_python)
 
 function show_default ()
 {
@@ -231,12 +335,15 @@ function show_help ()
     echo "  --with-build-top=directory build directory $(show_default $build_top)"
     echo "  --add directory add directory to library search path"
     echo "  --1bitsgd[=(yes|no)] use 1Bit SGD $(show_default ${default_use_1bitsgd})"
+    echo "  --asgd[=(yes|no)] use ASGD powered by Multiverso $(show_default $(default_use_asgd))"
     echo "  --cuda[=(yes|no)] use cuda GPU $(show_default $(default_use_cuda))"
+    echo "  --python[=(yes|no)] with Python bindings $(show_default $(default_use_python))"
     echo "  --with-cuda[=directory] $(show_default $(find_cuda))"
     echo "  --with-cub[=directory] $(show_default $(find_cub))"
     echo "  --with-gdk-include[=directory] $(show_default $(find_gdk_include))"
     echo "  --with-gdk-nvml-lib[=directory] $(show_default $(find_gdk_nvml_lib))"
     echo "  --with-cudnn[=directory] $(show_default $(find_cudnn))"
+    echo "  --with-nccl[=directory] $(show_default $(find_nccl))"
     echo "  --with-mkl[=directory] $(show_default $(find_mkl))"
     echo "  --with-mkl-sequential[=directory] $(show_default $(find_mkl))"
     echo "  --with-openblas[=directory] (experimental) $(show_default $(find_openblas))"
@@ -247,6 +354,12 @@ function show_help ()
     echo "  --with-openmpi[=directory] $(show_default $(find_openmpi))"
     echo "  --with-code-coverage[=(yes|no)] $(show_default ${default_use_code_coverage})"
     echo "  --with-boost[=directory] $(show_default $(find_boost))"
+    echo "  --with-protobuf[=directory] $(show_default $(find_protobuf))"
+    echo "  --with-py-versions=(space-separated list of 34, 35)"
+    echo "  --with-py34-path[=directory] $(show_default $(find_python 34))"
+    echo "  --with-py35-path[=directory] $(show_default $(find_python 35))"
+    echo "  --with-swig[=directory] $(show_default $(find_swig))"
+
     echo "Libraries search path:"
     for head in $(default_paths)
     do
@@ -304,6 +417,17 @@ do
             fi
             ;;
 
+        --asgd*)
+            if test x$optarg = xyes || test x$optarg = xno
+            then
+                enable_asgd=$optarg
+            else
+                echo "Invalid value for --asgd $optarg"
+                show_help
+                exit
+            fi
+            ;;
+
         --cuda*)
             if test x$optarg = xyes || test x$optarg = xno
             then
@@ -315,8 +439,87 @@ do
             fi
             ;;
 
+        --python*)
+            if test x$optarg = xyes || test x$optarg = xno
+            then
+                enable_python=$optarg
+            else
+                echo "Invalid value for --python $optarg"
+                show_help
+                exit
+            fi
+            ;;
+
+        --with-py-versions*)
+            enable_python=yes
+            if test "x$optarg" = "x"
+            then
+                echo "Mandatory parameter for --with-py-versions missing. Use '--python no' to disable Python support completely."
+                show_help
+                exit 1
+            else
+                for ver in $optarg
+                do
+                    case $ver in
+                        34 | 35)
+                            ;;
+                        *)
+                            echo "Invalid value for --with-py-versions $optarg: invalid version $ver"
+                            show_help
+                            exit
+                    esac
+                done
+                # TODO filter duplicates?
+                py_versions="$optarg"
+            fi
+            ;;
+
+        --with-py34-path*|--with-py35-path*)
+            enable_python=yes
+            py_version=${key:9:2}
+            if test x$optarg = x
+            then
+                py_paths[$py_version]=$(find_python $py_version)
+                if test x${py_paths[$py_version]} = x
+                then
+                    echo "Cannot find Python $py_version directory."
+                    echo "Please specify a value for $key"
+                    exit 1
+                fi
+            else
+                if check_python $py_version "$optarg"
+                then
+                    py_paths[$py_version]=$optarg
+                else
+                    echo "Invalid Python $py_version directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
+
+        --with-swig*)
+            have_swig=yes
+            if test x$optarg = x
+            then
+                swig_path=$(find_swig)
+                if test x$swig_path = x
+                then
+                    echo "Cannot find SWIG directory."
+                    echo "Please specify a value for --with-swig"
+                    exit 1
+                fi
+            else
+                if check_swig "$optarg"
+                then
+                    swig_path=$optarg
+                else
+                    echo "Invalid SWIG directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
+
         --with-cuda*)
-            have_cuda=yes
             enable_cuda=yes
             if test x$optarg = x
             then
@@ -337,6 +540,7 @@ do
                 fi
             fi
             ;;
+
         --with-cub*)
             have_cub=yes
             if test x$optarg = x
@@ -422,6 +626,28 @@ do
                 fi
             fi
             ;;
+        --with-nccl*)
+            have_nccl=yes
+            if test x$optarg = x
+            then
+                nccl_path=$(find_nccl)
+                if test x$nccl_path = x
+                then
+                    echo "Cannot find NCCL directory."
+                    echo "Please specify a value for --with-nccl"
+                    echo "NCCL can be downloaded from https://github.com/NVIDIA/nccl"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $nccl_check) = yes
+                then
+                    nccl_path=$optarg
+                else
+                    echo "Invalid NCCL directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
         --with-openmpi*)
               have_openmpi=yes
               if test x$optarg = x
@@ -434,15 +660,15 @@ do
                       exit 1
                   fi
               else
-  		if test $(check_dir $optarg $openmpi_check) = yes
- 		then
- 		    openmpi_path=$optarg
- 		else
- 		    echo "Invalid OpenMPI directory $optarg"
- 		    exit 1
- 		fi
- 	    fi
- 	    ;;
+  	if test $(check_dir $optarg $openmpi_check) = yes
+ 	then
+ 	    openmpi_path=$optarg
+ 	else
+ 	    echo "Invalid OpenMPI directory $optarg"
+ 	    exit 1
+ 	fi
+               fi
+           ;;
         --with-mkl*)
             have_mkl=yes
             mathlib=mkl
@@ -455,7 +681,7 @@ do
                 mkl_path=$(find_mkl)
                 if test x$mkl_path = x
                 then
-                    echo "Cannot find CNTK custom MKL directory"
+                    echo "Cannot find CNTK custom MKL directory (version $cntk_custom_mkl_version)"
                     echo "Please specify a value for --with-mkl"
                     exit 1
                 fi
@@ -496,17 +722,37 @@ do
             then
                 boost_path=$(find_boost)
                 if test x$boost_path = x
-                then 
+                then
                     echo "Cannot find Boost directory"
                     echo "Please specify a value for --with-boost"
                     exit 1
                 fi
             else
                 if test $(check_dir $optarg $boost_check) = yes
-                then 
+                then
                     boost_path=$optarg
                 else
                     echo "Invalid Boost directory $optarg"
+                    exit 1
+                fi
+             fi
+             ;;
+        --with-protobuf*)
+            if test x$optarg = x
+            then
+                protobuf_path=$(find_protobuf)
+                if test x$protobuf_path = x
+                then
+                    echo "Cannot find Protocol Buffers directory"
+                    echo "Please specify a value for --with-protobuf"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $protobuf_check) = yes
+                then
+                    protobuf_path=$optarg
+                else
+                    echo "Invalid Protocol Buffers directory $optarg"
                     exit 1
                 fi
              fi
@@ -618,15 +864,15 @@ fi
 # If no math library was specified, search for mkl
 if test x$have_mkl = xno && test x$have_openblas = xno
 then
-	mkl_path=$(find_mkl)
-	if test x$mkl_path = x
-	then
-		echo "Cannot find a CPU math library."
-		echo "Please specify --with-mkl, --with-mkl-sequential, --with-openblas with a path."
-		exit 1
-	else
-		mathlib=mkl
-	fi
+    mkl_path=$(find_mkl)
+    if test x$mkl_path = x
+    then
+        echo "Cannot find a CPU math library."
+        echo "Please specify --with-mkl, --with-mkl-sequential, --with-openblas with a path."
+        exit 1
+    else
+        mathlib=mkl
+    fi
 fi
 
 # If no cuda library specified, search for one
@@ -690,6 +936,55 @@ then
     fi
 fi
 
+if test $enable_python = yes && test x$swig_path = x
+then
+    swig_path=$(find_swig)
+    if test x$swig_path = x
+    then
+        echo 'Cannot locate SWIG (>= 3.0.10), which is required Python support.'
+        echo Check bindings/python/swig_install.sh for build instructions.
+        exit 1
+    fi
+fi
+
+if test $enable_python = yes
+then
+    # Fill unfilled default paths
+    [ -z "${py_paths[34]}" ] && find_python 34 && py_paths[34]=$(find_python 34)
+    [ -z "${py_paths[35]}" ] && find_python 35 && py_paths[35]=$(find_python 35)
+
+    # Unless there's a specified order or restriction, take all configured Python versions (old to new)
+    [ -z "$py_versions" ] && py_versions=${!py_paths[@]}
+    py_versions="$py_versions "
+
+    # Make sure each requested version is configured, remove other parts
+    for ver in 34 35
+    do
+        case $py_versions in
+            *$ver\ *)
+                # Build for version is requested, check if configured
+                if [ -z "${py_paths[$ver]}" ]
+                then
+                    echo Build for Python version $ver was requested, but is not configured.
+                    exit 1
+                fi
+                ;;
+            *)
+                # Build for version is not requested, unconfigure
+                unset -v py_paths[$ver]
+                ;;
+        esac
+    done
+fi
+
+if test $enable_cuda = yes && test x$nccl_path = x
+then
+    nccl_path=$(find_nccl)
+    if test x$nccl_path != x; then
+        echo Found NCCL at $nccl_path
+    fi
+fi
+
 if test x$opencv_path = x
 then
     opencv_path=$(find_opencv)
@@ -729,9 +1024,23 @@ then
     if test x$boost_path = x
     then
         echo Cannot locate Boost libraries
-        echo Unit tests will NOT be built.
+        echo ImageReader and Unit tests will NOT be built.
     else
         echo Found Boost at $boost_path
+    fi
+fi
+
+if test x$protobuf_path = x
+then
+    protobuf_path=$(find_protobuf)
+    if test x$protobuf_path = x
+    then
+        echo Cannot locate Protocol Buffers library. See
+        echo   https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux#protobuf
+        echo for installation instructions.
+        exit 1
+    else
+        echo Found Protocol Buffers at $protobuf_path
     fi
 fi
 
@@ -756,6 +1065,18 @@ if test $enable_cuda = yes ; then
     echo GDK_NVML_LIB_PATH=$gdk_nvml_lib_path >> $config
     echo CUB_PATH=$cub_path >> $config
     echo CUDNN_PATH=$cudnn_path >> $config
+    [ -z "$nccl_path" ] || echo NCCL_PATH=$nccl_path >> $config
+fi
+if test $enable_python = yes ; then
+    echo PYTHON_SUPPORT=true >> $config
+    echo SWIG_PATH=$swig_path/bin >> $config
+    # N.B. PYTHON_VERSIONS at least needs to be parseable by bash (cf. Tools/generate_build_info)
+    echo PYTHON_VERSIONS= >> $config
+    for ver in $py_versions
+    do
+        echo PYTHON_VERSIONS+=$ver >> $config
+        echo PYTHON${ver}_PATH=${py_paths[$ver]}/$py_check >> $config
+    done
 fi
 if test x$kaldi_path != x ; then
     echo KALDI_PATH=$kaldi_path >> $config
@@ -778,6 +1099,13 @@ fi
 if test x$boost_path != x; then
     echo BOOST_PATH=$boost_path >> $config
 fi
+if test x$protobuf_path != x; then
+    echo PROTOBUF_PATH=$protobuf_path >> $config
+fi
+
+if test $enable_asgd = yes ; then
+    echo CNTK_ENABLE_ASGD=true >> $config
+fi
 
 # If we are not in the configure directory, generate a trampoline Makefile
 makefile=$build_top/Makefile
@@ -794,5 +1122,7 @@ then
     printf '\t$(MAKE) -C $(dir) BUILD_TOP=$(BUILD_TOP) $@\n' >> $makefile
 fi
 echo run
-echo '>make -j all'
+echo '>make -j $(nproc) all'
 echo to build
+
+# vim:set expandtab tabstop=4 shiftwidth=4:
