fix comments from CR

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -316,6 +316,7 @@ function show_help ()
     echo "  --1bitsgd[=(yes|no)] use 1Bit SGD $(show_default ${default_use_1bitsgd})"
     echo "  --cuda[=(yes|no)] use cuda GPU $(show_default $(default_use_cuda))"
     echo "  --python[=(yes|no)] with Python bindings $(show_default $(default_use_python))"
+    echo "  --mpi[=(yes|no)] use MPI communication $(show_default ${default_use_mpi})"
     echo "  --with-cuda[=directory] $(show_default $(find_cuda))"
     echo "  --with-cub[=directory] $(show_default $(find_cub))"
     echo "  --with-gdk-include[=directory] $(show_default $(find_gdk_include))"
@@ -335,8 +336,6 @@ function show_help ()
     echo "  --with-py34-path[=directory] $(show_default $(find_python 34))"
     echo "  --with-py35-path[=directory] $(show_default $(find_python 35))"
     echo "  --with-swig[=directory] $(show_default $(find_swig))"
-
-    echo "  --mpi[=(yes|no)] use mpi communication $(show_default ${default_use_mpi})"
     echo "Libraries search path:"
     for head in $(default_paths)
     do
@@ -432,7 +431,7 @@ do
                         *)
                             echo "Invalid value for --with-py-versions $optarg: invalid version $ver"
                             show_help
-                exit
+                            exit
                     esac
                 done
                 # TODO filter duplicates?
@@ -656,14 +655,14 @@ do
             then
                 boost_path=$(find_boost)
                 if test x$boost_path = x
-                then 
+                then
                     echo "Cannot find Boost directory"
                     echo "Please specify a value for --with-boost"
                     exit 1
                 fi
             else
                 if test $(check_dir $optarg $boost_check) = yes
-                then 
+                then
                     boost_path=$optarg
                 else
                     echo "Invalid Boost directory $optarg"
@@ -688,7 +687,7 @@ do
                 else
                     echo "Invalid Protocol Buffers directory $optarg"
                     exit 1
-             fi
+                fi
              fi
              ;;
         --with-buildtype*)
@@ -785,15 +784,15 @@ fi
 # If no math library was specified, search for mkl
 if test x$have_mkl = xno && test x$have_openblas = xno
 then
-	mkl_path=$(find_mkl)
-	if test x$mkl_path = x
-	then
-		echo "Cannot find a CPU math library."
-		echo "Please specify --with-mkl, --with-mkl-sequential, --with-openblas with a path."
-		exit 1
-	else
-		mathlib=mkl
-	fi
+    mkl_path=$(find_mkl)
+    if test x$mkl_path = x
+    then
+        echo "Cannot find a CPU math library."
+        echo "Please specify --with-mkl, --with-mkl-sequential, --with-openblas with a path."
+        exit 1
+    else
+        mathlib=mkl
+    fi
 fi
 
 # If no cuda library specified, search for one
