Re-add OpenMPI changes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19,6 +19,10 @@ have_acml=no
 acml_path=
 acml_check=include/acml.h
 
+have_openmpi=no
+openmpi_path=
+openmpi_check=include/mpi.h
+
 # CNTK Custom MKL Version
 cntk_custom_mkl_version=1
 
@@ -83,6 +87,7 @@ default_cubs="cub-1.4.1"
 default_cudnns="cudnn-4.0"
 default_opencvs="opencv-3.1.0 opencv-3.0.0"
 default_libzips="libzip-1.1.2"
+default_openmpis="openmpi-1.10.1"
 
 function default_paths ()
 {
@@ -123,6 +128,11 @@ function find_dir ()
 function find_acml ()
 {
     find_dir "$default_acmls" "$acml_check"
+}
+
+function find_openmpi ()
+{
+    find_dir "$default_openmpis" "$openmpi_check"
 }
 
 function find_mkl ()
@@ -223,6 +233,7 @@ function show_help ()
     echo "  --with-kaldi[=directory] $(show_default $(find_kaldi))"
     echo "  --with-opencv[=directory] $(show_default $(find_opencv))"
     echo "  --with-libzip[=directory] $(show_default $(find_libzip))"
+    echo "  --with-openmpi[=directory] $(show_default $(find_openmpi))"
     echo "  --with-code-coverage[=(yes|no)] $(show_default ${default_use_code_coverage})"
     echo "Libraries search path:"
     for head in $(default_paths)
@@ -400,6 +411,27 @@ do
                 fi
             fi
             ;;
+        --with-openmpi*)
+              have_openmpi=yes
+              if test x$optarg = x
+              then
+                  openmpi_path=$(find_openmpi)
+                  if test x$openmpi_path = x
+  		then
+                      echo "Cannot find OpenMPI directory"
+                      echo "Please specify a value for --with-openmpi"
+                      exit 1
+                  fi
+              else
+  		if test $(check_dir $optarg $openmpi_check) = yes
+ 		then
+ 		    openmpi_path=$optarg
+ 		else
+ 		    echo "Invalid OpenMPI directory $optarg"
+ 		    exit 1
+ 		fi
+ 	    fi
+ 	    ;;
         --with-mkl*)
             have_mkl=yes
             mathlib=mkl
@@ -559,6 +591,19 @@ then
     fi
 fi
 
+# If no OpenMPI library specifies, search for one
+if test x$have_openmpi = xno
+then
+    openmpi_path=$(find_openmpi)
+    if test x$openmpi_path = x ; then
+        echo "Cannot find OpenMPI library."
+	echo "Please specify --with-openmpi with a path."
+	exit 1
+    else
+	echo Found OpenMPI at $openmpi_path
+    fi
+fi
+
 # If no cuda library specified, search for one
 if test x$enable_cuda = xyes && test x$cuda_path = x
 then
@@ -676,6 +721,9 @@ if test x$libzip_path != x ; then
 fi
 if test $enable_1bitsgd = yes ; then
     echo CNTK_ENABLE_1BitSGD=true >> $config
+fi
+if test x$openmpi_path != x ; then
+    echo OPENMPI_PATH=$openmpi_path >> $config
 fi
 if test $enable_code_coverage = yes ; then
     echo CNTK_CODE_COVERAGE=true >> $config
