Added NCCL support to SimpleDistGradAggregator

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16,6 +16,11 @@ enable_cuda=
 
 enable_python=
 
+# NCCL communication library
+have_nccl=no
+nccl_path=
+nccl_check=include/nccl.h
+
 # CNTK Custom MKL Version
 cntk_custom_mkl_version=2
 
@@ -96,6 +101,7 @@ default_boost="boost-1.60.0"
 
 # NOTE: Will get compilation errors with cuda-6.0
 default_cudas="cuda-7.5 cuda-7.0 cuda-6.5"
+default_nccls="nccl"
 default_kaldis="kaldi-trunk kaldi-c024e8aa"
 default_gdk_includes="include/nvidia/gdk"
 default_gdk_nvml_libs="src/gdk/nvml/lib"
@@ -160,6 +166,11 @@ function find_boost ()
 function find_protobuf ()
 {
     find_dir "$default_protobuf" "$protobuf_check"
+}
+
+function find_nccl ()
+{
+    find_dir "$default_nccls" "$nccl_check"
 }
 
 function find_cuda ()
@@ -318,6 +329,7 @@ function show_help ()
     echo "  --with-gdk-include[=directory] $(show_default $(find_gdk_include))"
     echo "  --with-gdk-nvml-lib[=directory] $(show_default $(find_gdk_nvml_lib))"
     echo "  --with-cudnn[=directory] $(show_default $(find_cudnn))"
+    echo "  --with-nccl[=directory] $(show_default $(find_nccl))"
     echo "  --with-mkl[=directory] $(show_default $(find_mkl))"
     echo "  --with-mkl-sequential[=directory] $(show_default $(find_mkl))"
     echo "  --with-openblas[=directory] (experimental) $(show_default $(find_openblas))"
@@ -584,6 +596,28 @@ do
                     cudnn_path=$optarg
                 else
                     echo "Invalid cuDNN directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
+        --with-nccl*)
+            have_nccl=yes
+            if test x$optarg = x
+            then
+                nccl_path=$(find_nccl)
+                if test x$nccl_path = x
+                then
+                    echo "Cannot find NCCL directory."
+                    echo "Please specify a value for --with-nccl"
+                    echo "NCCL can be downloaded from https://github.com/NVIDIA/nccl"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $nccl_check) = yes
+                then
+                    nccl_path=$optarg
+                else
+                    echo "Invalid NCCL directory $optarg"
                     exit 1
                 fi
             fi
@@ -883,6 +917,14 @@ then
     done
 fi
 
+if test $enable_cuda = yes && test x$nccl_path = x
+then
+    nccl_path=$(find_nccl)
+    if test x$nccl_path != x; then
+        echo Found NCCL at $nccl_path
+    fi
+fi
+
 if test x$opencv_path = x
 then
     opencv_path=$(find_opencv)
@@ -963,6 +1005,7 @@ if test $enable_cuda = yes ; then
     echo GDK_NVML_LIB_PATH=$gdk_nvml_lib_path >> $config
     echo CUB_PATH=$cub_path >> $config
     echo CUDNN_PATH=$cudnn_path >> $config
+    [-z "$nccl_path"] || echo NCCL_PATH=$nccl_path >> $config
 fi
 if test $enable_python = yes ; then
     echo PYTHON_SUPPORT=true >> $config
