Adding halide based binary convolution operators and its dependancies

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -47,6 +47,10 @@ protobuf_check=lib/libprotobuf.a
 mpi_path=
 mpi_check=include/mpi.h
 
+# Halide library
+halide_path=
+halide_check=include/Halide.h
+
 # Cuda-aware MPI
 # OPENMPI can auto-detect but not MVAPICH2
 cuda_gdr=no
@@ -131,6 +135,7 @@ default_protobuf="protobuf-3.1.0"
 default_libzips="libzip-1.1.2"
 default_swig="swig-3.0.10"
 default_mpi="mpi"
+default_halide="halide"
 
 function default_paths ()
 {
@@ -236,6 +241,11 @@ function find_libzip ()
 function find_mpi ()
 {
     find_dir "$default_mpi" "$mpi_check"
+}
+
+function find_halide ()
+{
+    find_dir "$default_halide" "$halide_check"
 }
 
 function is_hardlinked ()
@@ -356,6 +366,7 @@ function show_default ()
     fi
 }
 
+
 function show_help ()
 {
     echo "Usage: configure [options]"
@@ -394,6 +405,7 @@ function show_help ()
     echo "  --with-py36-path[=directory] $(show_default $(find_python 36))"
     echo "  --with-swig[=directory] $(show_default $(find_swig))"
     echo "  --with-mpi[=directory] $(show_default $(find_mpi))"
+    echo "  --with-halide[=directory] $(show_default $(find_halide))"
 
     echo "Libraries search path:"
     for head in $(default_paths)
@@ -917,6 +929,25 @@ do
                 fi
             fi
             ;;
+        --with-halide*)
+            if test x$optarg = x
+            then
+                halide_path=$(find_halide)
+                if test x$halide_path = x
+                then
+                    echo "Cannot find halide directory."
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $halide_check) = yes
+                then
+                    halide_path=$optarg
+                else
+                    echo "Invalid halide directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
         *)
             echo Invalid option $key
             show_help
@@ -1216,6 +1247,9 @@ if test x$protobuf_path != x; then
 fi
 if test x$mpi_path != x; then
     echo MPI_PATH=$mpi_path >> $config
+fi
+if test x$halide_path != x; then
+    echo HALIDE_PATH=$halide_path >> $config
 fi
 
 if test $enable_asgd = yes ; then
