Install Boost at /usr/local/boost-x.y.z on Docker Build unit tests only when Boost is available Configure Boost path in configure Address CR comments fix #678
This is a combination of 10 commits.
Adapt makefile to work with Docker container on Linux

This is a combination of 7 commits.
enable unit tests build

remove -liomp5 from math unit test

enable openmp

add -ldl

fix space error

add -dl for reader test

change order of -l

remove gdk installation

use /usr/local/lib as boost library path

Adapt path in unit tests on Linux
adapt path for Linux

adapt path on other test projects for Linux

remove extra blank line

add BOOST_PATH,and build unit tests based on BOOST_PATH

configure boost path

install Boost 1.60.0; use version variable instead of hardcoding.

add comments for different paths on Linux than on Windows.

restore installation of gdk, because the removal of gdk needs more changes and will be done in a separate check-in

use ifdef, fix typos

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -31,6 +31,10 @@ have_openblas=no
 openblas_path=
 openblas_check=include/openblas_config.h
 
+# Boost library
+boost_path=
+boost_check=include/boost/test/unit_test.hpp
+
 have_kaldi=no
 kaldi_path=
 kaldi_check=src/kaldi.mk
@@ -74,6 +78,8 @@ default_path_list="/usr /usr/local /opt /opt/local"
 default_acmls="acml5.3.1/ifort64_mp"
 default_mkls="CNTKCustomMKL"
 default_openblas=""
+
+default_boost="boost-1.60.0"
 
 # NOTE: Will get compilation errors with cuda-6.0
 default_cudas="cuda-7.5 cuda-7.0 cuda-6.5"
@@ -133,6 +139,11 @@ function find_mkl ()
 function find_openblas ()
 {
     find_dir "$default_openblas" "$openblas_check"
+}
+
+function find_boost ()
+{
+    find_dir "$default_boost" "$boost_check"
 }
 
 function find_cuda ()
@@ -224,6 +235,7 @@ function show_help ()
     echo "  --with-opencv[=directory] $(show_default $(find_opencv))"
     echo "  --with-libzip[=directory] $(show_default $(find_libzip))"
     echo "  --with-code-coverage[=(yes|no)] $(show_default ${default_use_code_coverage})"
+    echo "  --with-boost[=directory] $(show_default $(find_boost))"
     echo "Libraries search path:"
     for head in $(default_paths)
     do
@@ -448,6 +460,26 @@ do
                 fi
             fi
             ;;
+        --with-boost*)
+            if test x$optarg = x
+            then
+                boost_path=$(find_boost)
+                if test x$boost_path = x
+                then 
+                    echo "Cannot find Boost directory"
+                    echo "Please specify a value for --with-boost"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $boost_check) = yes
+                then 
+                    boost_path=$optarg
+                else
+                    echo "Invalid Boost directory $optarg"
+                    exit 1
+                fi
+             fi
+             ;;
         --with-buildtype*)
             have_buildtype=yes
             case $optarg in
@@ -641,6 +673,18 @@ then
     fi
 fi
 
+if test x$boost_path = x
+then
+    boost_path=$(find_boost)
+    if test x$boost_path = x
+    then
+        echo Cannot locate Boost libraries
+        echo Unit tests will NOT be built.
+    else
+        echo Found Boost at $boost_path
+    fi
+fi
+
 config=$build_top/Config.make
 echo Generating $config
 echo "#Configuration file for cntk" > $config
@@ -679,6 +723,9 @@ if test $enable_1bitsgd = yes ; then
 fi
 if test $enable_code_coverage = yes ; then
     echo CNTK_CODE_COVERAGE=true >> $config
+fi
+if test x$boost_path != x; then
+    echo BOOST_PATH=$boost_path >> $config
 fi
 
 # If we are not in the configure directory, generate a trampoline Makefile
