Updating build-and-test script and e2e tests to reflect new build directory layout

diff --git a/Scripts/build-and-test b/Scripts/build-and-test
--- a/Scripts/build-and-test
+++ b/Scripts/build-and-test
@@ -187,7 +187,9 @@ if [[ $BUILD == 1 ]]; then
             fi
             make -C $BUILD_DIR -j -f $MAKEFILE 1>&6 2>&7 || exit $?
         fi
-        chmod a+r $BUILD_FILE.*
+        if [[ $QUIET_BUILD == 1 ]]; then
+          chmod a+r $BUILD_FILE.*
+        fi
     done
 fi
 
@@ -215,18 +217,21 @@ if [[ $RUN == 1 ]]; then
             fi
             OUT_FILE="$RUN_FILE.$FLAVOR.$TARGET.out"
 
-            if ! [[ -f "./$FLAVOR_DIR/$BIN_NAME" ]]; then
+            BIN_PATH=$CNTK_ROOT/$FLAVOR_DIR/$BIN_NAME 
+            if ! [[ -f $BIN_PATH ]]; then
                 echo "============ ERROR: CNTK did not build properly for flavor ($FLAVOR)  ============"
+                echo "Missing file: $BIN_PATH"
                 exit 1
             fi
 
             echo "============ Running CNTK for ($FLAVOR) ($TARGET), output in ($RUN_FILE.*) ============"
+            cd $CNTK_ROOT/Demos
             rm -rf models
             if [[ $OS == "Windows_NT" ]]; then
                 # We have to use cygpath on Windows to modify the file paths into the format readable by cntk.
-                time ./$FLAVOR_DIR/$BIN_NAME configFile="`cygpath -w $CONF_FILE`" &>$OUT_FILE || exit $?
+                time $BIN_PATH configFile="`cygpath -w $CONF_FILE`" &>$OUT_FILE || exit $?
             else
-                time ./$FLAVOR_DIR/$BIN_NAME configFile=$CONF_FILE &>$OUT_FILE || exit $?
+                time $BIN_PATH configFile=$CONF_FILE &>$OUT_FILE || exit $?
             fi
             chmod a+r $RUN_FILE.*
 
