Adjust tests and project settigns for UWP remove hard tabs; add types in .gitattributes
update test, update baseline

use 01_OneHidden.model instead of 01_OneHidden.

update using CNTKOPENBLAS version 2

add a comment for using multiple inputs in C# example

improve project settings

fix settigns

diff --git a/Tests/EndToEndTests/EvalClientTests/CNTKLibraryCPPUWPEvalExamplesTests/run-test b/Tests/EndToEndTests/EvalClientTests/CNTKLibraryCPPUWPEvalExamplesTests/run-test
--- a/Tests/EndToEndTests/EvalClientTests/CNTKLibraryCPPUWPEvalExamplesTests/run-test
+++ b/Tests/EndToEndTests/EvalClientTests/CNTKLibraryCPPUWPEvalExamplesTests/run-test
@@ -5,8 +5,8 @@
 set -x
 
 if [ "$OS" != "Windows_NT" ]; then
-	echo 'This UWP test only runs on Windows.'
-	exit 1
+    echo 'This UWP test only runs on Windows.'
+    exit 1
 fi
 
 # This test uses a large dataset which is not part of the CNTK repository itself
@@ -23,21 +23,18 @@ VSTEST_CONSOLE=$(cygpath -au "$VS140COMNTOOLS\\..\\IDE\\CommonExtensions\\Micros
 test -x "$VSTEST_CONSOLE" || exit $?
 
 # Use pretrained model
-MODEL_FILE_DIR=$(cygpath -au "$HOMEPATH\\Documents")
-cp $TEST_DATA_DIR/PreTrainedModels/EvalModels/01_OneHidden $MODEL_FILE_DIR/01_OneHidden || exit $?
-ls $MODEL_FILE_DIR
+MODEL_FILE=$(cygpath -au "$USERPROFILE\\Documents\\01_OneHidden.model")
+cp $TEST_DATA_DIR/PreTrainedModels/EvalModels/01_OneHidden.model "$MODEL_FILE" || exit $?
 
 # Set CUDA_VISIBLE_DEVICES to exclude all gpu if running on cpu device
 [ "$TEST_DEVICE" == "cpu" ] && export CUDA_VISIBLE_DEVICES=-1
 
-"$VSTEST_CONSOLE" /inIsolation /Platform:x64 $(cygpath -aw "$TEST_BIN_DIR/CNTKLibraryCPPUWPEvalExamplesTests/CNTKLibraryCPPUWPEvalExamplesTests_1.0.1.0_x64_"$TEST_FLAVOR"_UWP.appx") || exit $?
+"$VSTEST_CONSOLE" /inIsolation /Platform:x64 $(cygpath -aw "$TEST_BIN_DIR/CNTKLibraryCPPUWPEvalExamplesTests/AppPackages/CNTKLibraryCPPUWPEvalExamplesTests_1.0.0.0_x64_"$TEST_FLAVOR"_UWP_Test/CNTKLibraryCPPUWPEvalExamplesTests_1.0.0.0_x64_"$TEST_FLAVOR"_UWP.appx") || exit $?
 
 
-rm -rf $MODEL_FILE_DIR/01_OneHidden || exit $?
-if [[ -f "$MODEL_FILE_DIR/01_OneHidden" ]]; then
-  echo "Failed to delete the model file $MODEL_FILE_DIR/01_OneHidden"
+rm -rf "$MODEL_FILE" || exit $?
+if [[ -f "$MODEL_FILE" ]]; then
+  echo "Failed to delete the model file $MODEL_FILE"
   exit 1
 fi
-ls $MODEL_FILE_DIR
-  
 exit 0
